### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by redna11** [bybit-exchange/pybit#142] opened 2023-05-03 08:51 UTC
HI, is there proxy support on pybit? if so, is there documentation or example for it. thx

**Comment by dextertd** [comment] 2023-05-03 18:54
Duplicate of #126

**Closed as completed by dextertd** 2023-05-03 18:54 UTC

**Comment by jkllx** [comment] 2025-07-11 07:37
```
from pybit.unified_trading import HTTP

session = HTTP(
            testnet=testnet,
            api_key=api_key,
            api_secret=api_secret,
        )

session.client.proxies.update(
    {
        'http': 'your proxy address',
        'https': 'your proxy address'
    }
)
```
