### ISSUE TITLE
Crypto module error 

### ISSUE THREAD

**Issue by urmatov74** [bybit-exchange/pybit#210] opened 2024-04-23 09:51 UTC
![image](https://github.com/bybit-exchange/pybit/assets/62984709/7699c8f7-563e-40dd-8da3-481432dcf7fc)

I am using the latest version (pybit 5.7.0)

**Comment by dextertd** [comment] 2024-04-23 10:13
Duplicate of  #167

**Closed as completed by dextertd** 2024-04-23 10:13 UTC
