### ISSUE TITLE
getting error to get spot_margin_trade_normal_get_interest_quota

### ISSUE THREAD

**Issue by kouchak-roni** [bybit-exchange/pybit#195] opened 2024-02-14 07:51 UTC
I am trying to fetch spot_margin_trade_normal_get_interest_quota for BTC but getting
2024-02-14 13:15:46 - pybit._http_manager - ERROR - Timestamp for this request is outside of the recvWindow. (ErrCode: 10002). Added 2.5 seconds to recv_window. 2 retries remain.
FailedRequestError: Bad request. retries exceeded maximum. (ErrCode: 400) (ErrTime: 07:45:56).
Request → GET https://api.bybit.com/v5/spot-cross-margin-trade/loan-info: coin=BTC.

**Comment by dextertd** [comment] 2024-02-29 11:23
Duplicate of https://github.com/bybit-exchange/pybit/issues/191

**Closed as completed by dextertd** 2024-02-29 11:23 UTC
