### ISSUE TITLE
Cannot authenticate private WebSocket subscription

### ISSUE THREAD

**Issue by helgenodland** [bybit-exchange/pybit#6] opened 2022-04-03 18:38 UTC
pybit-2.0.1 
python 3.8

applied API key/secret was valid for placing orders, so the key/secret should be ok.
problem:
...DEBUG Authorization for Inverse Perp (Auth) failed. Please check your API keys and restart.
...ERROR Couldn't subscribe to topic.Error: error:topic:position needs auth first.

" needs auth first??"  are there other methods to do auth?

```python
#https://github.com/bybit-exchange/pybit
from time import sleep
from pybit import inverse_perpetual
import logging

logging.basicConfig(filename="pybit3.log", level=logging.DEBUG,
                    format="%(asctime)s %(levelname)s %(message)s")

api_key = '*********************'
api_secret = '*****************************'
# Connect with authentication!
ws = inverse_perpetual.WebSocket(
    test=False,
    api_key=api_key,
    api_secret=api_secret,
    domain="bybit"
)

def handle_position(message):
    print(message)
ws.position_stream(handle_position)

while True:
    sleep(0.1)
#
# LOG output:
# DEBUG WebSocket Inverse Perp (Auth) closed.
# DEBUG WebSocket Inverse Perp (Auth) opened.
# DEBUG Authorization for Inverse Perp (Auth) failed. Please check your API keys and restart.
# ERROR Couldn't subscribe to topic.Error: error:topic:position needs auth first.
```

**Comment by helgenodland** [comment] 2022-04-04 17:16
SOLUTION?!
Wait until the next day, and it magically starts to work. 
I have no clue...

**Comment by dextertd** [comment] 2022-04-05 08:58
I can occasionally reproduce this, and it might be happening because pybit tries to authenticate and then subscribe to auth topics in quick succession. Adding a small delay to the authentication could fix this. Also some retry logic.

**Comment by Maxiviper117** [comment] 2022-05-16 19:55
Don't know if this would help, but I had a similar issue with the Auth Failed, turns out my recent Windows Reinstall led to the windows time clock being out of sync, did a manual sync in windows settings, and working again.

I guess the async function of the WebSocket could not correctly sync the server time with my PC's window clock time, so authentication failed.

**Comment by dextertd** [comment] 2022-08-24 16:45
This was fixed with this commit https://github.com/bybit-exchange/pybit/commit/fc6a9a13084a5300064a6455acb7062f7ceaaffe#diff-c1db9cd0f8057231f64be3a8da367f2cbf2666587a16cc7072348449e0e7fb7aR249

But can reopen the issue if any more reports.

**Closed as completed by dextertd** 2022-08-24 16:45 UTC
